# Generated by Django 4.2.3 on 2023-07-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_somedata_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
